### ISSUE TITLE
Missing "pmi_ngram.py" file

### ISSUE THREAD

**Issue by VincentDENGP** [shizhediao/T-DNA#1]
Hi, thanks for sharing the code. I'm trying to run your code but seems missing one file "pmi_ngram.py"? Does this file be supposed to implement by myself?

**Comment by happygirlzt** [comment]
Hi, thank you very much for sharing the code. I would appreciate it if you can share this `pmi_ngram.py`. Thanks.  @shizhediao

**Comment by shizhediao** [comment]
Hi, I have uploaded the `pmi_ngram.py`. Hope it helps.
This is an example script for extracting domain-specific words/ngrams and you may find more effective strategies to extract useful ngrams.
In addition, you could tune the hyper-parameters of `min_pmi`, `min_count`, `ngram_freq_threshold` to build a better domain-specific vocabulary list.
Sorry for my late reply!
