### ISSUE TITLE
Excuse me, how to get <task_name>.npy

### ISSUE THREAD

**Issue by MzY-1999** [shizhediao/T-DNA#2]
Excuse me, how to get <task_name>.npy

**Comment by shizhediao** [comment]
Hi, there are two steps:
1. Training word vectors using `fasttext` on the raw data following https://fasttext.cc/docs/en/unsupervised-tutorial.html.
```
$ ./fasttext skipgram -input data/fil9 -output result/fil9
```
2. Extracting the ngram embeddings from pre-trained models:

```
model = load_model(f"./{task_name}.bin")
ngram_file = open(f'./{task_name}.txt')
ngram_emb_path = f'./{task_name}.npy'
all_ngram_emb = []
for ngram in ngram_file:
    ngram = ngram.strip()
    ngram_list = ngram.split(' ')
    # print(ngram_list)

    # idx = 0
    for idx, ngram_word in enumerate(ngram_list):
        ft_word_emb = model.get_word_vector(ngram_word)
        if idx ==0:
            ngram_emb = ft_word_emb
        else:
            ngram_emb += ft_word_emb
    ngram_emb = ngram_emb/(idx+1)

    all_ngram_emb.append(ngram_emb)

all_ngram_emb_numpy = np.array(all_ngram_emb)
np.save(ngram_emb_path, all_ngram_emb_numpy)
```
This process is fast and easy to follow. I will update the code scripts and those files soon. 
Thanks!

**Comment by MzY-1999** [comment]
ok, thank you!!

**Comment by shizhediao** [comment]
Hi,
The processing [script](https://github.com/shizhediao/T-DNA/blob/main/TDNA/ngram_emb.py) and [these files](https://github.com/shizhediao/T-DNA/tree/main/ngram) have been uploaded.
Please check them.

Closed this issue and feel free to open a new one if you have more questions.

Thanks!
